apis:
  main@v1:
    root: docs/asset-bundle-registry-openapi.yaml

extends:
  - recommended

rules:
  security-defined: off
  info-license: off
  operation-4xx-response: warn
  no-unused-components: warn
