name: CI/CD on main branch

on:
  push:
    branches:
      - "main"

jobs:
  asset-bundle-registry-deployment:
    uses: decentraland/platform-actions/.github/workflows/apps-docker-next.yml@main
    with:
      service-name: asset-bundle-registry
      image-name: asset-bundle-registry
      deployment-environment: dev
    secrets: inherit
