name: Manual deployment

on:
  workflow_dispatch:
    inputs:
      deployment-environment:
        required: true
        type: choice
        options:
          - prd
          - stg
          - dev
        default: prd
        description: Environment
      tag:
        required: true
        default: "latest"
        type: string
        description: "Docker tag (quay.io)"

jobs:
  deployment:
    if: ${{ inputs.deployment-environment }}
    name: "Deploy asset-bundle-registry to: ${{ inputs.deployment-environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.deployment-environment }}
    steps:
      - name: Trigger deployment
        id: deploy
        uses: decentraland/dcl-deploy-action@main
        with:
          dockerImage: "quay.io/decentraland/asset-bundle-registry:${{ inputs.tag }}"
          serviceName: asset-bundle-registry
          env: ${{ inputs.deployment-environment }}
          token: ${{ secrets.GITHUB_TOKEN }}
