name: Manual deployment

on:
  workflow_dispatch:
    inputs:
      service-name:
        required: true
        type: choice
        options:
          - asset-bundle-registry
          - asset-bundle-registry-abgen
        default: asset-bundle-registry
        description: Service
      deployment-environment:
        required: true
        type: choice
        options:
          - prd
          - stg
          - dev
        default: prd
        description: Environment
      tag:
        required: true
        default: "latest"
        type: string
        description: "Docker tag (quay.io)"

jobs:
  deployment:
    if: ${{ inputs.deployment-environment }}
    name: "Deploy ${{ inputs.service-name }} to: ${{ inputs.deployment-environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.deployment-environment }}
    steps:
      - name: Trigger deployment
        id: deploy
        uses: decentraland/dcl-deploy-action@main
        with:
          # Both services run the same image; only the ECS service differs.
          dockerImage: "quay.io/decentraland/asset-bundle-registry:${{ inputs.tag }}"
          serviceName: ${{ inputs.service-name }}
          env: ${{ inputs.deployment-environment }}
          token: ${{ secrets.GITHUB_TOKEN }}
